# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'teamSelection.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 621)
        self.teamFrame = QtWidgets.QFrame(Dialog)
        self.teamFrame.setGeometry(QtCore.QRect(15, 230, 231, 141))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 240, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 240, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 240, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 240, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.teamFrame.setPalette(palette)
        self.teamFrame.setAutoFillBackground(True)
        self.teamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.teamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.teamFrame.setObjectName("teamFrame")
        self.teamLbl = QtWidgets.QLabel(self.teamFrame)
        self.teamLbl.setGeometry(QtCore.QRect(10, 10, 221, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 240, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.teamLbl.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.teamLbl.setFont(font)
        self.teamLbl.setObjectName("teamLbl")
        self.member1Tbx = QtWidgets.QTextEdit(self.teamFrame)
        self.member1Tbx.setGeometry(QtCore.QRect(10, 50, 171, 31))
        self.member1Tbx.setObjectName("member1Tbx")
        self.member2Tbx = QtWidgets.QTextEdit(self.teamFrame)
        self.member2Tbx.setGeometry(QtCore.QRect(10, 90, 171, 31))
        self.member2Tbx.setObjectName("member2Tbx")
        self.titleGraphic = QtWidgets.QGraphicsView(Dialog)
        self.titleGraphic.setGeometry(QtCore.QRect(15, 20, 970, 192))
        self.titleGraphic.setObjectName("titleGraphic")
        self.teamFrame2 = QtWidgets.QFrame(Dialog)
        self.teamFrame2.setGeometry(QtCore.QRect(280, 230, 231, 141))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 85, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.teamFrame2.setPalette(palette)
        self.teamFrame2.setAutoFillBackground(True)
        self.teamFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.teamFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.teamFrame2.setObjectName("teamFrame2")
        self.teamLbl2 = QtWidgets.QLabel(self.teamFrame2)
        self.teamLbl2.setGeometry(QtCore.QRect(10, 10, 221, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(86, 240, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.teamLbl2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.teamLbl2.setFont(font)
        self.teamLbl2.setObjectName("teamLbl2")
        self.member1Tbx2 = QtWidgets.QTextEdit(self.teamFrame2)
        self.member1Tbx2.setGeometry(QtCore.QRect(10, 50, 171, 31))
        self.member1Tbx2.setObjectName("member1Tbx2")
        self.member2Tbx2 = QtWidgets.QTextEdit(self.teamFrame2)
        self.member2Tbx2.setGeometry(QtCore.QRect(10, 90, 171, 31))
        self.member2Tbx2.setObjectName("member2Tbx2")
        self.teamFrame.raise_()
        self.member2Tbx.raise_()
        self.titleGraphic.raise_()
        self.teamFrame2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.teamLbl.setText(_translate("Dialog", "Team 1"))
        self.teamLbl2.setText(_translate("Dialog", "Team 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

